version: 0.2

env:
  variables:
    FOO: bar

phases:
  install:
    commands:
      - echo "---------- install"
      - pwd
      - "which yarn || curl -o- -L https://yarnpkg.com/install.sh | bash"
      - pwd
      - which node
      - which yarn
      - node --version
      - yarn --version
      - cd frontend && yarn
  build:
    commands:
      - pwd
      - echo "---------- build"
      - echo "Hello, $FOO"
      - cd frontend && yarn build
  post_build:
    commands:
      - echo "---------- post_build"

artifacts:
  files:
    - README.rdoc
    - Gemfile
    - frontend/dist/build.js
